include:
  - local: 'ci/maven-settings.yml'

stages:
  - install
  # - docker-build

# maven-install:
#   stage: install
#   image: $DOCKER_REGISTRY/minimal-ubuntu:latest
#   tags:
#     - docker-runner
#   variables:
#     MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
#   cache:
#     - key: cache-maven
#       paths:
#         - .m2/repository
#   before_script:
#     - mkdir -p $CI_PROJECT_DIR/.m2
#     - echo $MAVEN_SETTINGS  > $CI_PROJECT_DIR/.m2/settings.xml
#   script:
#     - mvn install -DskipTests --settings $CI_PROJECT_DIR/.m2/settings.xml
#   artifacts:
#     paths:
#       - openmetadata-dist/target
#   only:
#     refs:
#       - develop


docker-build:
  stage: install
  image: $DOCKER_REGISTRY/docker:24.0.5
  services:
    - name: $DOCKER_REGISTRY/docker:24.0.5-dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: "tcp://localhost:2375"
    # DOCKER_HOST: $DOCKER_HOST_URL
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  # dependencies:
  #   - maven-install
  # needs: ["maven-install"]
  tags:
    - docker-runner
  script:
    # - unset DOCKER_HOST
    - cat /lib/systemd/system/docker.service
    - ss -tulpn | grep dockerd
    - echo $DOCKER_HOST
    - docker info
    - docker build --tag $DOCKER_HOST_URL/openmetadata-server:latest -f docker/development/Dockerfile .
    - docker login -u=$DOCKER_HOST_USER -p=$DOCKER_HOST_TOKEN $DOCKER_HOST_URL
    - docker push $DOCKER_HOST_URL/openmetadata-server:latest
    - docker rmi -f $DOCKER_HOST_URL/openmetadata-server:latest
  only:
    refs:
      - develop

